name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: 4.4.0
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            GOOGLE_GENERATIVE_AI_API_KEY
          workingDirectory: apps/game-object
          packageManager: pnpm
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
